---
# group:
# system_group:
- name: Balanced-Users | Create user groups
  group:
    name: '{{ item.group | default(item.name) }}'
    system: '{{ item.system_group | default("no") }}'
    state: 'present'
  with_flattened:
    - balanced_users_default
    - balanced_users_global_admins
    - balanced_users_default_groups_list
    - balanced_users_global_users
    - balanced_users_group_vars_specific_users
    - balanced_users_host_vars_specific_users
  when: |
    item.name and (item.state is undefined or
                   (item.state is defined and item.state != "absent"))
