---
# tasks file for balanced-users

# - groups are created first and removed last, because when we say that a user
#   is absent, the group needs to be removed *after* the user is removed,
#   not *before*, though, this could probably be done via handler
- include: groups_create.yml
  when: balanced_users_enabled

- include: users.yml
  when: balanced_users_enabled

- include: ssh_keys.yml
  when: balanced_users_enabled

- include: dotfiles.yml
  when: balanced_users_enabled

- include: groups_delete.yml
  when: balanced_users_enabled

- include: rm_default_ec2_keyname.yml
  when: balanced_users_enabled and balanced_users_rm_default_ec2_keyname